version: 2.1
executorType: machine
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - restore_cache:
          key: kp-dependency-build-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run build
          command: |
            mvn clean install -DskipTests -DCLOUD_STORE_GROUP_ID=$CLOUD_STORE_GROUP_ID -DCLOUD_STORE_ARTIFACT_ID=$CLOUD_STORE_ARTIFACT_ID -DCLOUD_STORE_VERSION=$CLOUD_STORE_VERSION
      - save_cache:
          paths:
            - ~/.m2
          key: kp-dependency-build-cache-{{ checksum "pom.xml" }}

  unit-tests:
    machine:
      image: ubuntu-2004:202201-02
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          key: kp-dependency-test-cache-{{ checksum "pom.xml" }}

      - run:
          name: Setup environment and run tests
          command: bash vmsetup.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
          paths:
            - ~/.m2
          key: kp-dependency-test-cache-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/test-results

  sonar-analysis:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - restore_cache:
          key: kp-dependency-test-cache-{{ checksum "pom.xml" }}
      - run:
          name: Setup environment and run SonarQube analysis
          command: bash sonar-analysis.sh
      - save_cache:
          paths:
            - ~/.m2
          key: kp-dependency-test-cache-{{ checksum "pom.xml" }}

  deploy-sonarqube:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - run:
          name: Deploy SonarQube
          command: |
            docker run -d --name sonarqube -p 9000:9000 sonarqube:latest

workflows:
  version: 2.1
  build-then-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - sonar-analysis:
          requires:
            - unit-tests
      - deploy-sonarqube:
          requires:
            - sonar-analysis
