version: 2.1
executorType: machine
jobs:
  kp-build:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node-browsers-legacy
      - image: circleci/redis:latest
    steps:
      - checkout
      - restore_cache:
          key: kp-dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Setup environment
          command: bash vmsetup.sh
      - run:
          name: Run Test cases
          command: bash run-testcases.sh

workflows:
  version: 2.1
  workflow:
    jobs:
      - kp-build
