apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          env: ## Env variables to pass
            - name: NEO4J_dbms_security_auth__enabled
              value: "false"
          ports:
            - containerPort: 7474
              name: cypher-port
            - containerPort: 7687
              name: bolt-port-1
            - containerPort: 8687
              name: bolt-port-2
          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: cypher-shell-port
      port: 7474
      targetPort: 7474
    - name: bolt-port-1
      port: 7687
      targetPort: 7687
    - name: bolt-port-2
      port: 8687
      targetPort: 8687
  selector:
    app: {{ .Chart.Name }}